import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import News from "@/components/News";
import SessionWrapper from "@/components/SessionWrapper";
import { Providers } from "./Provider";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SessionWrapper>
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <div className="flex justify-between max-w-7xl mx-auto">
            <div className="sticky top-0 hidden sm:inline border-r-2 border-slate-200 dark:border-slate-600 h-screen">
              <Sidebar/>
            </div>
            <div className="w-2xl flex-1">
              {children}
            </div>
            <div className="lg:flex-col p-3 sticky top-0 h-screen border-l-2 border-slate-200 dark:border-slate-600  hidden lg:flex w-[24rem]">
              <div className="sticky top-0 dark:bg-black bg-white py-2">
                <input type="test" placeholder="Search" className="bg-gray-100 border border-gray-200 rounded-3xl test-sm w-full px-4 py-2"/>
              </div>
              <News/>
            </div>
          </div>
        </Providers>
      </body>
    </html>
    </SessionWrapper>
  );
}
